### PR TITLE
[lichess improvements, changeable depth] sending moves via websocket, fixes, improvements

### PR DESCRIPTION
**Pull request by xHeaven**
- Added the possibility to send the bot's moves via Lichess' built-in websocket client.
	- This way the bot can run even in the background or on a second monitor, it won't move the mouse, so you can enjoy other things while the bot is playing for you.
	- Currently only works for Lichess.
	- **Doesn't work in Puzzles** as Puzzles don't send network data via websocket.

- Fixed `is_game_over()` not working with locales other than English.
- Fixed `click_puzzle_next()` not working when a specific "Continue training" button comes up when Lichess wants you to rate the puzzle.
- Improved `get_move_list()`
	- Extracted the code part that finds the `move_list_elem` element into getters. One getter for normal games, one getter for puzzles.
	- Fixed circlejerking trying to figure out whether we are playing puzzles or not while we already have a `is_game_puzzles()` method that can check it.
	- Added a `set_moves_tag_name()` method that dynamically gets the element's tag name from the site that contains the moves. Ref:
		- https://github.com/PanagiotisIatrou/chess-auto-bot/issues/7
		- https://github.com/PanagiotisIatrou/chess-auto-bot/pull/11
- Stockfish's depth can be changed now. The default is 15, the minimum is 1, the maximum is 20.

### CODE REVIEW

**Comment by Rottefar** [comment]
At where do i change the depth of stockfish?
Nothing in the GUI has changed..

MB if im just stupid

**Comment by PanagiotisIatrou** [comment]
Hello @xHeaven. Thanks again for contributing!
There are a lot of added features but I noticed some things that made the bot not function correctly. I got them fixed with this commit ([935e4c9](https://github.com/PanagiotisIatrou/chess-auto-bot/pull/13/commits/935e4c9cfdeca1be5f1a2ad22dd6768d22d2589c)):
- You forgot the move_count argument on the `ws_execute_move` which I added and renamed the function to `make_mouseless_move`. I also made this function abstract in case the chess.com socket gets implemented in the future.
- Some other bugs in the lichess_grabber.py, such as the initialization of `self.tag_name` and an empty list returned at `get_puzzles_move_list_elem`. I also cleaned the file a bit and formatted it.

I also thought it would make sense to give the option of whether or not to make the bot move the mouse or not with a checkbox as it often makes for a cool effect. I plan to make the movement of the mouse more smooth and more human-like in the future.
I also added a check on the start button which doesn't let you continue if you have checked the mouseless mode and selected the chess.com website.

Tell me if you try it or notice anything weird in the code. There were lots of changes involved in this pull request so there might be some bugs involved.

**Comment by xHeaven** [comment]
> Hello @xHeaven. Thanks again for contributing! There are a lot of added features but I noticed some things that made the bot not function correctly. I got them fixed with this commit ([935e4c9](https://github.com/PanagiotisIatrou/chess-auto-bot/pull/13/commits/935e4c9cfdeca1be5f1a2ad22dd6768d22d2589c)):
> 
> * You forgot the move_count argument on the `ws_execute_move` which I added and renamed the function to `make_mouseless_move`. I also made this function abstract in case the chess.com socket gets implemented in the future.
> * Some other bugs in the lichess_grabber.py, such as the initialization of `self.tag_name` and an empty list returned at `get_puzzles_move_list_elem`. I also cleaned the file a bit and formatted it.
> 
> I also thought it would make sense to give the option of whether or not to make the bot move the mouse or not with a checkbox as it often makes for a cool effect. I plan to make the movement of the mouse more smooth and more human-like in the future. I also added a check on the start button which doesn't let you continue if you have checked the mouseless mode and selected the chess.com website.
> 
> Tell me if you try it or notice anything weird in the code. There were lots of changes involved in this pull request so there might be some bugs involved.

Hey @PanagiotisIatrou ,

## I'm okay with these
- as for the `make_mouseless_move`, that's a good name, I like that much better than my original one. I didn't make it abstract, because I didn't look into Chess.com's code yet, also I wasn't sure if you want this specific function to be available (and *needed*) in all Grabber instances.
I'm good with that.
- I indeed forgot the move_count argument, good catch, thanks.
- I've also forgot to add the self.tag_name initialization, as I've already had it implemented in my local codebase. Whoops. Good catch again.

## This one though...
- The empty list return in the get_normal_move_list_elem method was on purpose.
	- The logic would be, if we find the element with the `l4x` tag name, then we found the `move_list_element` and it has moves already. We return the `move_list_element`.
	- If we didn't find the `l4x` element, an exception is being thrown, in which we check for the `rm6` element. If the `rm6` element exists, that means we have the move_list_element itself, but we have no moves so far (hence we can't find the `l4x` element that is supposed to be *under* the `rm6` element and holds the moves) so we return an empty list AKA "empty move list". This is being checked in the 64rd line of [src/grabbers/lichess_grabber.py](https://github.com/PanagiotisIatrou/chess-auto-bot/pull/13/commits/935e4c9cfdeca1be5f1a2ad22dd6768d22d2589c#diff-e4350ccf4763181b67a9a0c0c874d68f1293d72e0057994647300bf8c2478a30): `if move_list_elem is None -> or not move_list_elem <-:`
	- If we can't even find the `rm6` element, an exception is being thrown and we `return None` because something is clearly wrong there.
	- This way you don't need the `if tag == "div":` check in the 71st line in [src/grabbers/lichess_grabber.py](https://github.com/PanagiotisIatrou/chess-auto-bot/pull/13/commits/935e4c9cfdeca1be5f1a2ad22dd6768d22d2589c#diff-e4350ccf4763181b67a9a0c0c874d68f1293d72e0057994647300bf8c2478a30).
- The checkbox for enabling/disabling mouseless interaction on Lichess is a great addition.

What do you think? Let me know, and then if we agree, I'll merge the changes into my local codebase and test it out so that we can merge the changes into the main branch later on.

**Comment by PanagiotisIatrou** [comment]
Hello @xHeaven.

Yep, you are right. It honestly just weirded me out how a function returning an element might return an empty list. To me, it seemed like this return belonged to a function like `get_move_list` and I thought it was just a mistake in the pull request.

Good to know that `not [] == True` though, I would have never thought of it that way 😄 
Maybe change the `not move_list_elem` check to `move_list_elem == []` to make it a bit more obvious?

Anyhow, yes change it back to an empty list and I can merge this request.

**Comment by xHeaven** [comment]
> Hello @xHeaven.
> 
> Yep, you are right. It honestly just weirded me out how a function returning an element might return an empty list. To me, it seemed like this return belonged to a function like `get_move_list` and I thought it was just a mistake in the pull request.
> 
> Good to know that `not [] == True` though, I would have never thought of it that way 😄 Maybe change the `not move_list_elem` check to `move_list_elem == []` to make it a bit more obvious?
> 
> Anyhow, yes change it back to an empty list and I can merge this request.

That makes sense, I probably should've put a comment in there.
Yes, `not []` evaluates as `True`, *because the `if` statement evaluates everything in a boolean context*. Think of it like there is an implicit call to the built-in `bool()` method.
Eg.: `bool([]) == False` is True.
Empty lists/containers are *falsy*, meaning their boolean evaluation will be False. Docs regarding this: https://docs.python.org/3/library/stdtypes.html#truth-value-testing

I'm pushing the requested change in a minute so you can merge the PR.

**Comment by xHeaven** [comment]
Requested change committed, PR can now be merged.

**Comment by PanagiotisIatrou** [comment]
I tested the changes and it works great!
I also updated the README with the mouseless mode and the depth selection.
Again, thanks for all these new great features, I will merge the PR to main.

**Pull request merged**
