### PR TITLE
Chess.com fix

### PR DESCRIPTION
**Pull request by MarcusM2092**

### CODE REVIEW

**Comment by PanagiotisIatrou** [comment]
Hello @MarcusM2092,

When I try to run the "Cant find Chrome. You need to have Chrome installed for this to work." pops up.
In a closer look I can see that you have changed some parts to Firefox instead of chrome, but the part that checks chrome still exists. Did you also try to replace Chrome for every aspect?

**Comment by vsauce974** [comment]
@MarcusM2092 Do you have any idea how to fix this? I changed the hardcoded values to my directory, but it still says, 'Can't find Chrome. You need to have Chrome installed for this to work.' However, after running 'pip install --upgrade webdriver-manager,' it now opens the browser in the directory I hardcoded. Despite this, it doesn't recognize it as a browser, and I still get the error 'Can't find Chrome. You need to have Chrome installed for this to work,' even with the browser open.

**Comment by MarcusM2092** [comment]
> Hello @MarcusM2092,
> 
> When I try to run the "Cant find Chrome. You need to have Chrome installed for this to work." pops up. In a closer look what is probably causing the issue is the fact that you have hardcoded this line:
> 
> ```python
> options.add_argument(r"--user-data-dir=C:\Users\marcus\AppData\Local\Google\Chrome\User Data")
> ```
> 
> which is not working for users other than marcus and also it is not OS independent. I understand this can be a bit hard to solve, so I suggest you revoke the changes regarding the autosave function so that I can push the fixes for chess.com that are working as expected. You can always just make another PR in the future with this feature.

i can just upload my changes I've made so far then you can go of that

**Comment by MarcusM2092** [comment]
heres a link to download it because github can be a pain sometimes https://drive.google.com/drive/folders/1lcns12bJxjpq5dzEhKLDeoZeQrznQAc9?usp=sharing

**Comment by MarcusM2092** [comment]
> @MarcusM2092 Do you have any idea how to fix this? I changed the hardcoded values to my directory, but it still says, 'Can't find Chrome. You need to have Chrome installed for this to work.' However, after running 'pip install --upgrade webdriver-manager,' it now opens the browser in the directory I hardcoded. Despite this, it doesn't recognize it as a browser, and I still get the error 'Can't find Chrome. You need to have Chrome installed for this to work,' even with the browser open.

you need to download chrome and install it

**Comment by vsauce974** [comment]
> > @MarcusM2092 Do you have any idea how to fix this? I changed the hardcoded values to my directory, but it still says, 'Can't find Chrome. You need to have Chrome installed for this to work.' However, after running 'pip install --upgrade webdriver-manager,' it now opens the browser in the directory I hardcoded. Despite this, it doesn't recognize it as a browser, and I still get the error 'Can't find Chrome. You need to have Chrome installed for this to work,' even with the browser open.
> 
> you need to download chrome and install it

i obviously have chrome installed i said chrome already opened when i updated webdriver-manager and the hard coded values but the error still pops up which is the reason why im confused

**Comment by PanagiotisIatrou** [comment]
> heres a link to download it because github can be a pain sometimes https://drive.google.com/drive/folders/1lcns12bJxjpq5dzEhKLDeoZeQrznQAc9?usp=sharing

You have to make another commit to this PR revoking the changes regarding auto save. It is really hard for me to figure out what differences the code in the link you sent has, and it is not as simple as copying and pasting.

**Comment by vsauce974** [comment]
> > > @MarcusM2092 Do you have any idea how to fix this? I changed the hardcoded values to my directory, but it still says, 'Can't find Chrome. You need to have Chrome installed for this to work.' However, after running 'pip install --upgrade webdriver-manager,' it now opens the browser in the directory I hardcoded. Despite this, it doesn't recognize it as a browser, and I still get the error 'Can't find Chrome. You need to have Chrome installed for this to work,' even with the browser open.
> > 
> > 
> > you need to download chrome and install it
> 
> I obviously have Chrome installed. I mentioned that Chrome opened when I updated webdriver-manager and the hard-coded values, but the error still appears, which is why I'm confused. If it's working for you, may I know the version of Chrome you have installed? I have the latest version, which is 123.0.6312.59 (Official Build) (64-bit).

Nvm its working for me now, i modified the code a bit

**Comment by PanagiotisIatrou** [comment]
Hello @MarcusM2092,

I removed the auto save feature so that I can push the fixes for chess.com. You can always make another PR with that feature if you want.

I also renamed some variables, reformatted some code, readded the window icon and reset some of the configuration values you changed, aiming for a base version that works seamlessly with low spec PC's as well.

Thank you for your support to this project

**Pull request merged**
